### ISSUE TITLE
`swiftmailer/swiftmailer` is EOL

### ISSUE THREAD

**Issue by Rotzbua** [getgrav/grav-plugin-email#158]
`swiftmailer` is EOL and archived https://github.com/swiftmailer/swiftmailer .
So no further updates or *security* fixes.

They recommend to migrate to `Symfony Mailer` https://symfony.com/doc/current/mailer.html or other library.

**Comment by rhukster** [comment]
We are well aware of this.  This is something that we're looking to move to for Grav 2.

**Comment by danaos** [comment]
Maybe just switch the default engine in email,yaml till then?

**Comment by rhukster** [comment]
If you switch to the GPM to **testing** rather than the default **stable**, you will find an Email v4.0.0-rc.1 that contains the initial release for Email with Syfmony/Mailer.  Also there are a few custom transport engine plugins (Sendgrid, Mailersend, Amazon SES, and Mandrill/Mailchimp) with more coming.

Please test this!!!!
